monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "alsa_card.pci-0000_00_03.0"
            }
        ]
        
        actions = {
            update-props = {
                node.description = "HDMI"
                node.nick = "HDMI"
                device.disabled = true
            }
        }
    }
]
