monitor.alsa.rules = [
    {
        matches = [
            { node.name = "alsa_card.usb-M-Audio_Fast_Track-00" }
        ]
        
        actions = {
            update-props = {
                node.description = "FastTrack"
                node.nick = "FastTrack"
            }
        }
    },
    {
        matches = [
            { node.name = "alsa_input.usb-M-Audio_Fast_Track-00.pro-input-0" }
        ]
        
        actions = {
            update-props = {
                node.description = "FT-in"
                node.nick = "FT-in"
            }
        }
    },
    {
        matches = [
            { node.name = "alsa_output.usb-M-Audio_Fast_Track-00.pro-output-0" }
        ]
        
        actions = {
            update-props = {
                node.description = "FT-out"
                node.nick = "FT-out"
            }
        }
    }
]
