monitor.alsa.rules = [
    {
        matches = [
            { node.name = "alsa_output.pci-0000_00_1b.0.analog-stereo" }
        ]
        actions = {
            update-props = {
                node.description = "Laptop-out"
                node.nick = "Laptop-out"
            }
        }
    },
    {
        matches = [
            { node.name = "alsa_input.pci-0000_00_1b.0.analog-stereo" }
        ]
        actions = {
            update-props = {
                node.description = "Laptop-in"
                node.nick = "Laptop-in"
            }
        }
    }
]
