alias uu="sudo pacman -Syu"
alias cs=cdls
alias brc="source ~/.bashrc"
alias cls="clear"
alias shutdown="systemctl poweroff"
alias poweroff="systemctl poweroff"
alias reboot="systemctl reboot"
alias spotify="spotify --no-zygote --no-gpu"
alias ls="ls --color=always"
alias vim="nvim"
alias ivpn="new_iitis_vpn"
