--vim.api.nvim_create_autocmd({"BufEnter","BufAdd","BufNew","BufNewFile","BufWinEnter"}, {
--    group = vim.api.nvim_create_augroup("TS_FOLD_WORKAROUND", {}),
--    callback = function()
--        vim.opt.foldmethod = "expr"
--        vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
--    end
--})
--
--require'nvim-treesitter.configs'.setup {
--    ensure_installed = { "bash", "c", "lua", "luadoc", "vim", "vimdoc", "nginx", "rust", "sql", "ssh_config", "terraform", "tmux", "yaml", "query", "python", "dockerfile" },
--    highlight = {enable=true},
--}
--
--vim.opt.foldenable = false
