font=Hack Nerd Font Propo:size=12
bold-text-in-bright=no
# workers=<number of logical CPUs>

[main]
initial-window-mode=maximized

[scrollback]
lines=0
multiplier=0

[url]
launch=/usr/bin/librewolf ${url}

[key-bindings]
spawn-terminal=none

