font=NotoSansM Nerd Font Mono:size=12
bold-text-in-bright=no

[main]
include=/usr/share/foot/themes/tokyonight-night
initial-window-mode=maximized

[url]
launch=zen ${url}
# https://onet.pl

[key-bindings]
spawn-terminal=none

[scrollback]
lines=0
multiplier=0

