#Nie używaj ~/.config/pipewire/pipewire.conf.
#Definiuj rzeczy w ~/.config/pipewire/pipewire.conf.d/.
#
#Sekcje słowników są merge'owane, a listy sklejane ze sobą.
#node.rules              device.rules
#
#

context.properties = {
    default.clock.min-quantum = 128
    default.clock.rate = 44100
}

