import = [ "~/.config/alacritty/alacritty-theme/themes/tokyo-night.toml" ]


[window]
opacity = 0.9
decorations = "None"
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 30

[font]
size = 12

[font.normal]
family = "SauceCodePro Nerd Font Mono"
